version: "3.9"

services:
  adminer:
    image: adminer
    container_name: admin
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - my_network
  db:
    image: postgres:14-alpine
    container_name: postgressql
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=offer_db
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my_network
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  my_network:
volumes:
  pgdata:
